export const PRODUCTS = [
  {
    id: 'equity-mf',
    category: 'Mutual Funds',
    name: 'Equity Mutual Funds',
    description: 'Diversified portfolios investing in high-growth Indian equities for maximum long-term capital appreciation.',
    highlight: 'Returns: 12-15% p.a. (Historical)',
    icon: 'TrendingUp',
  },
  {
    id: 'debt-mf',
    category: 'Mutual Funds',
    name: 'Debt Mutual Funds',
    description: 'Invest in stable fixed-income securities and corporate bonds for consistent yield and capital protection.',
    highlight: 'Returns: 6-8% p.a. (Low Risk)',
    icon: 'Layers',
  },
  {
    id: 'sip',
    category: 'Investments',
    name: 'SIP (Systematic Investment Plan)',
    description: 'Build a regular investing habit with monthly contributions compounding your wealth over time.',
    highlight: 'Min. Investment: ₹500 / month',
    icon: 'Coins',
  },
  {
    id: 'term-insurance',
    category: 'Insurance',
    name: 'Term Insurance',
    description: 'High-cover life protection policies ensuring complete financial security for your family in your absence.',
    highlight: 'Coverage up to: ₹2 Crore',
    icon: 'Shield',
  },
  {
    id: 'health-insurance',
    category: 'Insurance',
    name: 'Health Insurance',
    description: 'Comprehensive medical coverage shields you and your family from unexpected healthcare and hospital expenses.',
    highlight: 'Cashless Network: 10,000+ Hospitals',
    icon: 'Activity',
  },
  {
    id: 'nps',
    category: 'Investments',
    name: 'NPS (National Pension System)',
    description: 'Government-backed pension scheme offering secure retirement corpus accumulation along with tax benefits.',
    highlight: 'Additional Tax Benefit: Section 80CCD',
    icon: 'Award',
  },
  {
    id: 'elss',
    category: 'Mutual Funds',
    name: 'ELSS (Tax Saving Funds)',
    description: 'Equity mutual funds that qualify for tax deductions under Section 80C with the shortest lock-in period.',
    highlight: 'Lock-in: Only 3 Years (80C Eligible)',
    icon: 'Percent',
  },
  {
    id: 'business-loan',
    category: 'Loans',
    name: 'Business Loans',
    description: 'Secure capital for inventory, equipment, or scaling business operations with hassle-free collateral requirements.',
    highlight: 'Interest Rates from: 10.5% p.a.',
    icon: 'Briefcase',
  },
  {
    id: 'home-loan',
    category: 'Loans',
    name: 'Home Loans',
    description: 'Attractive interest rates and flexible tenures to help you buy, construct, or renovate your dream home.',
    highlight: 'Tenure: Up to 30 Years',
    icon: 'Home',
  },
  {
    id: 'fixed-income',
    category: 'Investments',
    name: 'Fixed Deposits & Bonds',
    description: 'Safe, predictable investment options with guaranteed payouts and zero market volatility risk.',
    highlight: 'Guaranteed Interest: Up to 7.8% p.a.',
    icon: 'Lock',
  },
];
