export const ROUTES = {
  HOME:                '/',
  ABOUT:               '/about',
  SERVICES:            '/services',
  SERVICE_FINANCIAL:   '/services/financial-planning',
  SERVICE_RETIREMENT:  '/services/retirement-planning',
  SERVICE_INVESTMENT:  '/services/investment-management',
  SERVICE_MUTUAL:      '/services/mutual-fund-sip',
  SERVICE_TAX:         '/services/tax-planning',
  SERVICE_LOANS:       '/services/corporate-retail-loans',
  SERVICE_INSURANCE:   '/services/insurance-solutions',
  SERVICE_NRI:         '/services/nri-investment',
  SERVICE_PORTFOLIO:   '/services/portfolio-review',
  SERVICE_ESTATE:      '/services/estate-planning',
  PRODUCTS:            '/products',
  CALCULATORS:         '/calculator',
  CALC_INVESTMENT:     '/calculators/investment',
  CALC_MUTUAL:         '/calculators/mutual-funds',
  CONTACT:             '/contact',
};
