import { ROUTES } from './routes';

export const SERVICES = [
  {
    id: 'financial-planning',
    title: 'Financial Planning',
    description: 'Establish smart financial goals, create a realistic budget, and manage your overall net worth.',
    href: '/services#financial-planning',
    icon: 'LineChart',
    focusPoints: ['Goal setting', 'Budgeting & cash flow', 'Net worth analysis'],
  },
  {
    id: 'retirement-planning',
    title: 'Retirement Planning',
    description: 'Design a stress-free retirement strategy using corpus calculation, pension options, and NPS advisory.',
    href: '/services#retirement-planning',
    icon: 'HeartHandshake',
    focusPoints: ['Corpus calculation', 'Pension plan selection', 'National Pension System (NPS)'],
  },
  {
    id: 'investment-management',
    title: 'Investment Management',
    description: 'Grow wealth steadily through custom portfolio construction and optimal asset allocation strategies.',
    href: '/services#investment-management',
    icon: 'TrendingUp',
    focusPoints: ['Custom portfolios', 'Strategic asset allocation', 'Risk management'],
  },
  {
    id: 'mutual-fund-sip',
    title: 'Mutual Fund & SIP Advisory',
    description: 'Make informed investments with systematic plans, expert fund selection, and active NAV monitoring.',
    href: '/services#mutual-fund-sip',
    icon: 'Coins',
    focusPoints: ['Fund research & selection', 'SIP discipline', 'NAV and returns monitoring'],
  },
  {
    id: 'tax-planning',
    title: 'Tax Planning',
    description: 'Legally minimize tax liabilities using ELSS, Section 80C deductions, and efficient ITR planning.',
    href: '/services#tax-planning',
    icon: 'Percent',
    focusPoints: ['Section 80C and standard deductions', 'Equity Linked Savings Scheme (ELSS)', 'ITR and HRA planning'],
  },
  {
    id: 'corporate-retail-loans',
    title: 'Corporate & Retail Loans',
    description: 'Secure funding for personal or business growth via home loans, business loans, and property backing.',
    href: '/services#corporate-retail-loans',
    icon: 'Briefcase',
    focusPoints: ['Business expansion loans', 'Residential home loans', 'Loans against property (LAP)'],
  },
  {
    id: 'insurance-solutions',
    title: 'Insurance Solutions',
    description: 'Protect what matters most with term plans, health insurance, ULIPs, and provider comparisons.',
    href: '/services#insurance-solutions',
    icon: 'Umbrella',
    focusPoints: ['Term life insurance', 'Comprehensive health coverage', 'ULIP & endowment plan analysis'],
  },
  {
    id: 'nri-investment',
    title: 'NRI Investment Services',
    description: 'Tailored India-focused wealth management for NRIs covering FCNR, NRE/NRO, and FEMA compliance.',
    href: '/services#nri-investment',
    icon: 'Globe',
    focusPoints: ['FCNR deposits', 'NRE/NRO accounts management', 'FEMA compliance & tax repatriation'],
  },
  {
    id: 'portfolio-review',
    title: 'Portfolio Review & Rebalancing',
    description: 'Keep investments aligned with annual reviews, target drift correction, and exit load minimization.',
    href: '/services#portfolio-review',
    icon: 'RefreshCw',
    focusPoints: ['Annual performance review', 'Asset drift correction', 'Exit load & tax optimization'],
  },
  {
    id: 'estate-planning',
    title: 'Estate Planning',
    description: 'Ensure smooth wealth transition to your loved ones using wills, nominations, and trust setup.',
    href: '/services#estate-planning',
    icon: 'FileText',
    focusPoints: ['Will drafting', 'Nominee synchronization', 'Succession and inheritance planning'],
  },
];
